export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE';

export const SAVE_PROJECTS = 'SAVE_PROJECTS';
export const SET_VIEWED_PROJECET = 'SET_VIEWED_PROJECET';
