export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE';

export const SAVE_PROJECTS = 'SAVE_PROJECTS';
export const SET_VIEWED_PROJECET = 'SET_VIEWED_PROJECET';

export const GET_PROJECTS_BUILDS_REQUEST = 'GET_PROJECTS_BUILDS_REQUEST';
export const GET_PROJECTS_BUILDS_SUCCESS = 'GET_PROJECTS_BUILDS_SUCCESS';
export const GET_PROJECTS_BUILDS_FAILURE = 'GET_PROJECTS_BUILDS_FAILURE';
export const SAVE_PROJECTS_BUILDS = 'SAVE_PROJECTS_BUILDS';

export const REBUILD_PROJECT_REQUEST = 'REBUILD_PROJECT_REQUEST';
export const REBUILD_PROJECT_SUCCESS = 'REBUILD_PROJECT_SUCCESS';
export const REBUILD_PROJECT_FAIL = 'REBUILD_PROJECT_FAIL';

export const UPDATE_PROJECT_STEPS_REQUEST = 'UPDATE_PROJECT_STEPS_REQUEST';
export const UPDATE_PROJECT_STEPS_SUCCESS = 'UPDATE_PROJECT_STEPS_SUCCESS';
export const UPDATE_PROJECT_STEPS_FAIL = 'UPDATE_PROJECT_STEPS_FAIL';
export const SAVE_PROJECT_STEPS = 'SAVE_PROJECT_STEPS';
