FROM ubuntu:latest
RUN apt-get update -y && apt-get install -y python-pip python3 python3-dev python3-pip python-dev build-essential git
COPY . /app
WORKDIR /app
RUN pip3 install -r requirements.txt && find . -name '*.pyc' -type f -delete
